version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #build: .
    environment:
      PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

# version: '3'
# services:

#   web:
#     # image: nginx:1.19.10
#     image: nginx:1.19.10-alpine
#     depends_on:
#       - app
#     ports:
#       - "8080:80"
#     volumes:
#       - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
#       - ./html:/var/www/html
#       - ./html:/usr/share/nginx/html

#   app:
#     image: php:7-fpm-alpine
#     volumes:
#       - ./html:/var/www/html
#       - ./html:/usr/share/nginx/html
#       - ./docker/app/php.ini:/usr/local/etc/php/php.ini
#       - ./docker/app/web.conf:/usr/local/etc/php-fpm.d/www.conf
